### ISSUE TITLE
Connecting to azure npm private feed

### ISSUE THREAD

**Issue by k2snowman69** [renovatebot/config-help#496]
### Which Renovate are you using? x the right box:

- [X] Renovate Open Source CLI
- [ ] WhiteSource Renovate App
- [ ] Renovate Pro
- [ ] Other (please write below)

### Which platform are you using? x the right box:

- [ ] GitHub.com
- [ ] GitHub Enterprise
- [ ] GitLab.com
- [ ] GitLab self-hosted
- [ ] Bitbucket Server
- [ ] Bitbucket Cloud
- [X] Azure DevOps

### Have you checked the logs? Don't forget to include them if relevant

Yes, I'm getting a 401 from the azure service when attempting to access my private npm feed

### What would you like to do?

I'm trying to access a private npm feed that I have setup in Azure. I saw the [question related to nuget](https://github.com/renovatebot/config-help/issues/203) and ended up with the following config

```
module.exports = {
  autodiscover: true,
  endpoint: "https://dev.azure.com/snowcoders/",
  token: "<azure token>",
  hostRules: [
    {
      domainName: "github.com",
      hostType: "github",
      token: "<github token>"
    },
    {
      hostName: "snowcoders.pkgs.visualstudio.com",
      hostType: "azure",
      token: "<azure token>"
    }
  ],
  onboardingConfig: {
    extends: ["@snowcoders"]
  },
  verbose: true,
  logLevel: "debug",
  platform: "azure"
};
```

However for the host rule for snowcoders.pkgs.visualstudio.com doesn't seem to be right as it 401s. Below is the error message I get for the dependency lookup.

```
INFO: Dependency lookup failure: unauthorized (repository=test-pipeline/test-pipeline)
       "pkgUrl": "https://snowcoders.pkgs.visualstudio.com/_packaging/snowcoders/npm/registry/husky",
       "authInfoType": undefined,
       "authInfoToken": undefined,
       "err": {
         "name": "HTTPError",
         "host": "snowcoders.pkgs.visualstudio.com",
         "hostname": "snowcoders.pkgs.visualstudio.com",
         "method": "GET",
         "path": "/_packaging/snowcoders/npm/registry/husky",
         "protocol": "https:",
         "url": "https://snowcoders.pkgs.visualstudio.com/_packaging/snowcoders/npm/registry/husky",
         "gotOptions": {
           "path": "/_packaging/snowcoders/npm/registry/husky",
           "protocol": "https:",
           "slashes": true,
           "auth": null,
           "host": "snowcoders.pkgs.visualstudio.com",
           "port": null,
           "hostname": "snowcoders.pkgs.visualstudio.com",
           "hash": null,
           "search": null,
           "query": null,
           "pathname": "/_packaging/snowcoders/npm/registry/husky",
           "href": "https://snowcoders.pkgs.visualstudio.com/_packaging/snowcoders/npm/registry/husky",
           "headers": {
             "user-agent": "https://github.com/renovatebot/renovate",
             "cache-control": "no-cache",
             "accept": "application/json",
             "accept-encoding": "gzip, deflate"
           },
```

So the question here is how am I supposed to set my auth token to access the pipeline exactly?

**Comment by rarkins** [comment]
npm is a special case where `.npmrc` files are used instead. Do you have a `.npmrc` file that is used either on CI or locally when developing?

**Comment by k2snowman69** [comment]
Yep, each repository has an npmrc that points to their private feed. I'm also running this via node on my personal box so I'm surprised renovatr doesn't have access even though I do.

Are you saying I need to add a .npmrc next to the config.js that I use to configure renovate?

**Comment by rarkins** [comment]
If you've got a `.npmrc` in your home directory and you run via node and not Docker, then Renovate should be picking it up. You can't add a `.npmrc` file next to `config.js` but you could add a `npmrc` field inside your `config.js`.

**Comment by k2snowman69** [comment]
I don't have an npmrc file in my home directory, I have it per repository  as the registry changes depending on the repository.

However I am running via node and it's definitely not picking up on my already logged in credentials. 

The new config looks something like this:

```
let azureToken = "...";
let githubToken = "...";

module.exports = {
  autodiscover: true,
  endpoint: "https://dev.azure.com/snowcoders/",
  token: azureToken,
  hostRules: [
    {
      domainName: "github.com",
      hostType: "github",
      token: githubToken
    },
    {
      hostName: "snowcoders.pkgs.visualstudio.com",
      hostType: "azure",
      token: azureToken
    }
  ],
  onboardingConfig: {
    extends: ["@snowcoders"]
  },
  npmrc:
    "registry=https://snowcoders.pkgs.visualstudio.com/_packaging/snowcoders/npm/registry/\nalways-auth=true",
  verbose: true,
  logLevel: "debug",
  platform: "azure"
};

```

**Comment by rarkins** [comment]
It's not "already logged in credentials" if the .npmrc is not in your home directory. Renovate runs against the github version of each repository and not your local clone of it.

The `npmrc` you configure needs to include credentials too.

**Comment by k2snowman69** [comment]
Okay, just checked the .npmrc file in my home directory and it definitely has a line for my private npm feed with an auth token on it. I tried copying the contents of that npmrc as the string for the `npmrc` property in my config which still resulted in a 401.

**Comment by rarkins** [comment]
If the npmrc file has more than one line, then replace line feeds with `\n` before  copying it into config file. If it still doesn't work then you might need to download the source and debug it locally.

**Comment by k2snowman69** [comment]
Sorry this one is long but hopefully it explains my debug path: 

### Part 1 - No npmrc in config
To start off I removed the npmrc property from my config so that my config is pretty basic:
```
module.exports = {
  autodiscover: true,
  endpoint: "https://dev.azure.com/snowcoders/",
  token: azureToken,
  hostRules: [
    {
      domainName: "github.com",
      hostType: "github",
      token: githubToken
    }
  ],
  onboardingConfig: {
    extends: ["@snowcoders"]
  },
  verbose: true,
  logLevel: "debug",
  platform: "azure"
};
```

I just debugged the packaged source code. Specifically ended up in 
node_modules\renovate\dist\datasource\npm\get.js

First it enters here when it's running mergeRenovateConfig (assuming it's generating the overall renovate config) and getNpmrc() returns null
 - @snowcoders/renovate-config
 - renovate-config-group
 - renovate-config-monorepo
 - renovate-config-packages
 All of which hit the public registry

 Now when it actually starts renovating my repository it seems that `getNpmrc()` has loaded the npmrc file from the repository and is now using that as it's default.

```
{
    always-auth:true,
    registry:"https://snowcoders.pkgs.visualstudio.com/_packaging/snowcoders/npm/registry/"
}
```

Since it's using the npmrc from the repository which was [setup using these instructions](https://docs.microsoft.com/en-us/azure/devops/artifacts/npm/npmrc?view=azure-devops&tabs=windows) it doesn't know the auth token as that's defined on my `%USERPROFILE%/.npmrc`. This means that when it attempts to actually access that registry it gets a 401 as it's not sending the auth token along.

This leads me to ask when does renovate load the auth tokens from the `%USERPROFILE%/.npmrc` if the auth tokens are stored on the local box but not within the repository themselves?

### Part 2 - Add npmrc to config containing registry

```
{
  autodiscover: true,
  endpoint: "https://dev.azure.com/snowcoders/",
  token: azureToken,
  hostRules: [
    {
      domainName: "github.com",
      hostType: "github",
      token: githubToken
    }
  ],
  onboardingConfig: {
    extends: ["@snowcoders"]
  },
  npmrc:
    "registry=https://snowcoders.pkgs.visualstudio.com/_packaging/snowcoders/npm/registry/",
  verbose: true,
  logLevel: "debug",
  platform: "azure"
};
```

In this flow, because the auth token doesn't exist upfront, renovate fails when it's running `mergeRenovateConfig`

### Part 3 - Add npmrc to config containing registry and auth token

In this scenario I copied the auth token from my .npmrc file into my renovate config along with the registry url
```
{
  autodiscover: true,
  endpoint: "https://dev.azure.com/snowcoders/",
  token: azureToken,
  hostRules: [
    {
      domainName: "github.com",
      hostType: "github",
      token: githubToken
    }
  ],
  onboardingConfig: {
    extends: ["@snowcoders"]
  },
  npmrc:
    "//snowcoders.pkgs.visualstudio.com/_packaging/snowcoders/npm/registry/:_authToken=bloopy.bloopy.bloopy\nregistry=https://snowcoders.pkgs.visualstudio.com/_packaging/snowcoders/npm/registry/",
  verbose: true,
  logLevel: "debug",
  platform: "azure"
}
```

This resulted in the exact same situation as the first scenario. Once the renovation starts on the repository, the repository npmrc overwrites the initial npmrc which is defined in the config and results in a 401 as that config doesn't contain an auth token (nor shouldn't).

### Conclusion

I'm unsure what should happen here. One solution which seems like overkill but maybe the correct one is:

1. Take the repository npmrc
1. Merge it with the renovate npmrc property
1. Merge it with the %USERPROFILE%/.npmrc

And then determine the auth information

**Comment by rarkins** [comment]
Right now `npmrc` configs are not merged/combined/concatenated. So ultimately Renovate picks one and that's the one it uses. If your registry= instruction is separate from your token then only one can be used and in both cases it would fail. Until we improve this, you need to make sure that whatever npmrc that Renovate is using has both the registry= directive (so that Renovate knows where to look) and authentication information too, so that it knows how to authenticate with your custom registry.

**Comment by k2snowman69** [comment]
Cool, I opened a PR to add hostRules functionality to the npm datasource. Kudos on how easy it was to do that! The hostRules config is amazingly simple!

**Comment by rarkins** [comment]
Let’s keep discussing on your PR in the main repo !
