### ISSUE TITLE
Renovate With Nexus Repo

### ISSUE THREAD

**Issue by sakshan** [renovatebot/config-help#561]
### Which Renovate are you using?

Renovate Open Source CLI

Other (please write below)

### Which platform are you using?

GitHub Enterprise

### What would you like to do?

Hi Renovate,

I am doing Renovate POC for our Organization. I have deployed renovate, instead of looking in to internet for new version, We want to look into our internal Nexus repository. Could you please let us know how to configure this in renovate ?

**Comment by rarkins** [comment]
Search the docs for “npmrc”

**Comment by sakshan** [comment]
As per the instruction provided in the doc, Have added npmrc in renovate.json 
 "npmrc": "//nexus.****.com/repository/npm-all/:_authToken=wEhSI7qAl2awblq2pA-RlRiFcyf9lvr-yA_JMjwPU64W"

We are seeing in logs, still its going to internet 


DEBUG: manager.fetchUpdates() (repository=****/node-npm-http-web)
--
  | WARN: Datasource failure (repository=***/node-npm-http-web)
  | "datasource": "npm",
  | "lookupName": "body-parser",
  | "err": {
  | "name": "TimeoutError",
  | "code": "ETIMEDOUT",
  | "host": "registry.npmjs.org",
  | "hostname": "registry.npmjs.org",
  | "method": "GET",

**Comment by viceice** [comment]
You need to configure the default registry too.

Please provide all relevant configs and debug logs.
You can replace private strings with `***` if required.

**Comment by sakshan** [comment]
Here is my logs. I am gettin
[renovate_error.log](https://github.com/renovatebot/config-help/files/4289806/renovate_error.log)
 error "Failed to look up dependency"

**Comment by viceice** [comment]
Can please share your configuration?

Also try to update your repo with a local npm client and your npmrc and share the results.

**Comment by viceice** [comment]
**Tasks**
- [ ] Check for valid SSL certificate of your nexus
- [ ] Test your auth token with local npm client
- [ ] Share your config with masked private urls / tokens / passwords

Try the following:
```json
{
  "npmrc": "//nexus.****.com/repository/npm-all/:_authToken=<place_token_here>\nregistry=https//nexus.****.com/repository/npm-all/"
}
```

**Comment by sakshan** [comment]
Have changed the  above configuration. I am getting error "Failed to look up dependency" Attached logs 
[renovate_error2.log](https://github.com/renovatebot/config-help/files/4294438/renovate_error2.log)

**Comment by viceice** [comment]
@sakshan Because you do not share your configuration and do not do our troublöe shooting steps we assume you have some wrong configs.

We can't help you without requested information, so i will close this issue.

**Comment by sakshan** [comment]
@viceice 
Here is the configuration file. I am getting error "lookup failed".


kind: ConfigMap
apiVersion: v1
metadata:
  name: js-configmap
data:
  config.js: |
    module.exports = {
      platform: 'github',
      endpoint: 'https://github.****.com/api/v3',
      logLevel: 'trace',
      includeForks: true,
      repositories: ['***-org/npmdemo'],
      encrypted: {
      npmToken: "******"
      },
      npmrc: "registry=https://nexus.***.com/repository/npmjs-proxy/\n//nexus.****.com/repository/npmjs-proxy:_authToken=${NPM_TOKEN}"
     };

**Comment by viceice** [comment]
You shouldn't encrypt the npmtoken with the self hosted renovate cli. You need to place it in the npmrc config.

**Comment by viceice** [comment]
@sakshan Use follwing `npmrc` config (do not encrypt it)

```json
{
  "npmrc": "registry=https://nexus.***.com/repository/npmjs-proxy/\n//nexus.****.com/repository/npmjs-proxy/:_authToken=XXX-TOKEN-XXX"
}
```
